[package]
name = "codegem"
version = "0.1.0"
edition = "2021"
description = "A small code generation library"
license = "MPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
